version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prepa-data-api:
    build: .
    environment:
      ANALYTICS_DB_HOST: postgres
      ANALYTICS_DB_PORT: 5432
      ANALYTICS_DB_NAME: analytics_db
      ANALYTICS_DB_USER: postgres
      ANALYTICS_DB_PASSWORD: postgres
      SOURCE_DB_HOST: host.docker.internal
      SOURCE_DB_PORT: 5432
      SOURCE_DB_NAME: edupath
      SOURCE_DB_USER: postgres
      SOURCE_DB_PASSWORD: postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    ports:
      - "8001:8001"

  airflow-init:
    image: apache/airflow:2.9.3
    entrypoint: ["/bin/bash", "-c"]
    command: ["airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"]
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/analytics_db
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/analytics_db
    command: ["airflow", "webserver"]
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags

  airflow-scheduler:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/analytics_db
    command: ["airflow", "scheduler"]
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags

volumes:
  pgdata:
